### ISSUE TITLE
Unexpected re-renders during collection fetch

### ISSUE THREAD

**Issue by brumm** [rakannimer/react-firebase#11]
Hey,

Thanks for making this!

I noticed that my app was re-rendering many times on initial load, and after changing a document, which was being rendered by a `FirestoreCollection`.

You can observe the behavior like this:

```js
<FirestoreCollection path="bookmarks">
  {({ isLoading, value }) => {
    if (isLoading) {
      return <Loading />
    } else {
      console.log(value.length)
      return null
    }
  }}
</FirestoreCollection>
```

Assuming you have a couple of documents in `bookmarks/` it should count up to the length of the collection.

It seems this happens because `setState` is being called for each document in the collection [here](https://github.com/rakannimer/react-firebase/blob/fd22fac9bfb6969bbb0913621077877f01279c21/modules/firestore/src/components/FirestoreProvider.tsx#L56) and each setState triggers a re-render.

Is this by design? The current behavior was unexpected for me, as I assumed it would only re-render once and add the documents in one transaction.

**Comment by rakannimer** [comment]
Hey @brumm,

Thanks for reporting this and investigating it 👍 

I think you're right it should do it in one transaction instead of one for each document.

If you have time, a PR would be very much appreciated ! 

Otherwise, I will look at this as soon as I have the time to.

Cheers !

**Comment by rakannimer** [comment]
Can you try 0.4.0 and let me know if it's acting as you expect ? 

Cheers :)

**Comment by brumm** [comment]
Hey,

Sorry, I was meaning to create a PR a couple of days ago but life got in the way.
The changes are looking good! Can confirm that it adds all documents in one transaction. Thanks!

**Comment by manoadamro** [comment]
> Hey,
> I am still experiencing this behavior when I have a where clause in my statement
> I'm using v0.5.4
> 
> ```dart
> <FirestoreCollection path="/users" where={{ field: 'userId', operator: '==', value: id }}>
>     {data => {
>       console.log(data)
>     }}
> </FirestoreCollection>
> ```

same issue here, this is spamming so much that the event loop is getting blocked up and my 500ms time outs are taking 5-10 seconds.
