### ISSUE TITLE
Firestore "timestampsInSnapshots setting now defaults to true" console error

### ISSUE THREAD

**Issue by isotopeee** [rakannimer/react-firebase#15]
I'm using `firebase@5.9.3` and there's this console error when using the `FirestoreProvider`.

![image](https://user-images.githubusercontent.com/17417116/55956337-5278a980-5c96-11e9-8f66-5f51ce711c66.png)

I believe this line causes it: https://github.com/rakannimer/react-firebase/blob/397320d3866b1e0f34df5489ef2f61ee9565e470/modules/firestore/src/components/FirestoreProvider.tsx#L114

**Comment by rakannimer** [comment]
Thanks for catching & reporting this ! Should be fixed in 0.5.3 👍
